language: php

php:
    - '5.6'
    - '7.1'

sudo: required

services:
    - docker

before_install:
    - docker build -t phptest -f ./docker/Dockerfile .
    - docker run -d -p 80:80 --name php-sample phptest
    - docker ps -a
    - echo $DOCKER_HOST
    - curl http://localhost

script:
    - ./lint.sh src
