language: php

php:
    - '7.3'

sudo: required

services:
    - docker

before_install:
    - docker --version
    - docker-compose --version
    - docker build -t cantonimobi -f ./docker/Dockerfile .
    - docker run -d -p 80:80 --name mobitest cantonimobi
    - docker ps -a
    - curl -i --head http://localhost

script:
    - ./lint.sh src
    - docker run --rm --link mobitest:web linkchecker/linkchecker --timeout 5 --check-extern --verbose --no-robots http://web/
