language: php

php:
    - '7.3'

sudo: required

services:
    - docker

before_install:
    - docker --version
    - docker-compose --version
    - docker build -t cantonimobi -f ./docker/Dockerfile .
    - docker run -d -p 80:80 --name mobitest cantonimobi
    - docker pull ktbartholomew/link-checker
    - docker ps -a
    - curl http://localhost

script:
    - ./lint.sh src
    - docker run --rm --link mobitest:web ktbartholomew/link-checker http://web/ -c 20
