#!/bin/bash

echo Stopping
running=$(docker ps -aq -f 'name=mobitest')

if [ "$running" != "" ]
then
    docker stop $running
    docker rm $running
else
	echo nothing to stop
fi
docker rmi cantonimobi
