<?php
$links = array(
array("url"=>"http://www.amexmobile.com/", "title"=>"American Express", "new"=>""), 
array("url"=>"http://bofa.mobi/", "title"=>"Bank of America", "new"=>""), 
array("url"=>"http://www.barclays.mobi/", "title"=>"Barclays", "new"=>""), 
//array("url"=>"http://m.capitalone.com/", "title"=>"Capital One", "new"=>""), 
array("url"=>"http://m.chase.com/", "title"=>"Chase Mobile", "new"=>""), 
array("url"=>"http://www.directtextbook.com/mobile.php", "title"=>"Direct Textbook Mobile", "new"=>""), 
//array("url"=>"https://wireless.etrade.com/etrade/", "title"=>"E*TRADE", "new"=>""), 
array("url"=>"http://wireless.fidelity.com/", "title"=>"Fidelity", "new"=>""), 
array("url"=>"http://mobile.huntington.com/", "title"=>"Huntington Bank", "new"=>""), 
array("url"=>"http://www.marketwatch.com/m/", "title"=>"MarketWatch.com", "new"=>""), 
array("url"=>"https://paypal.com/", "title"=>"PayPal", "new"=>""), 
array("url"=>"https://mtrading.scottrade.com/", "title"=>"Scottrade", "new"=>""), 
array("url"=>"http://mobile.slate.com/", "title"=>"Slate", "new"=>""), 
array("url"=>"https://m.usbank.com/", "title"=>"U.S. Bank", "new"=>""), 
array("url"=>"http://mobile.usaa.com/", "title"=>"USAA Mobile", "new"=>""), 
array("url"=>"https://mobile.wellsfargo.com/", "title"=>"Wells Fargo", "new"=>""), 
);
