<?php
$links = array(
array("url"=>"https://m.ask.com/", "title"=>"Ask", "new"=>""),
array("url"=>"https://m.bing.com/", "title"=>"Bing", "new"=>""),
array("url"=>"https://duckduckgo.com/lite", "title"=>"DuckDuckGo", "new"=>""),
array("url"=>"https://www.google.com/xhtml", "title"=>"Google", "new"=>""),
array("url"=>"https://mowser.com/", "title"=>"Mowser", "new"=>""),
//array("url"=>"https://us.m.yahoo.com/p/search", "title"=>"Yahoo", "new"=>""),
);
