<?php
$links = array(
array("url"=>"http://m.ask.com/", "title"=>"Ask", "new"=>""), 
array("url"=>"http://m.bing.com/", "title"=>"Bing", "new"=>""), 
array("url"=>"http://m.clusty.com/", "title"=>"Clusty Mobile Search", "new"=>""), 
array("url"=>"http://www.google.com/xhtml", "title"=>"Google", "new"=>""), 
array("url"=>"http://mowser.com/", "title"=>"Mowser", "new"=>""), 
array("url"=>"http://mobile.technorati.com/", "title"=>"Technorati", "new"=>""), 
array("url"=>"http://us.m.yahoo.com/p/search", "title"=>"Yahoo", "new"=>""), 
array("url"=>"http://m.yippy.com/", "title"=>"Yippy", "new"=>""), 
);
