<?php
$links = array(
array("url"=>"http://www.brighthand.com/mobile/", "title"=>"Brighthand", "new"=>""), 
array("url"=>"http://m.cnet.com/", "title"=>"CNET", "new"=>""), 
array("url"=>"http://m.engadget.com/", "title"=>"Engadget", "new"=>""), 
array("url"=>"http://m.gsmarena.com/", "title"=>"GSMArena.com", "new"=>""), 
array("url"=>"http://m.joystiq.com/", "title"=>"Joystiq", "new"=>""), 
array("url"=>"http://www.dslreports.com/mspeed", "title"=>"Mobile speed test", "new"=>""), 
array("url"=>"http://www.palminfocenter.com/mobile/", "title"=>"PalmInfocenter", "new"=>""), 
array("url"=>"http://slashdot.org/palm/", "title"=>"Slashdot", "new"=>""), 
array("url"=>"http://techmeme.com/m/", "title"=>"Techmeme", "new"=>""), 
array("url"=>"http://ubergizmo.mobi/", "title"=>"Ubergizmo", "new"=>""), 
//array("url"=>"http://www.wired.com/news_drop/palmpilot/", "title"=>"Wired News", "new"=>""), 
);
