<?php
$links = array(
array("url"=>"http://wap.accuweather.com/", "title"=>"AccuWeather", "new"=>""), 
array("url"=>"http://foreca.mobi/", "title"=>"ForeCA Weather", "new"=>""), 
array("url"=>"http://mobile.weather.gov/", "title"=>"National Weather Service", "new"=>""), 
array("url"=>"http://www.ssec.wisc.edu/data/paw/", "title"=>"PDA Animated Weather", "new"=>""), 
array("url"=>"http://xhtml.weather.com/xhtml/", "title"=>"The Weather Channel", "new"=>""), 
array("url"=>"http://m.wund.com/", "title"=>"Weather Underground", "new"=>""), 
);
